### ISSUE TITLE
outbound api return 500 response

### ISSUE THREAD

**Issue by lixiaojun0226** [sap-archive/com.sap.openSAP.hana5.example#3]
Hi, 
I use the demo to exploy outbound restful api by creating xsjs ,

but it return 500, any other configuration should be set
![b0e8c22a-9e1a-11e7-9f62-fca48fe26934](https://user-images.githubusercontent.com/10444859/30798241-715ee388-a20b-11e7-9a30-797c68f6c347.png)

Regarts,
June

**Comment by jung-thomas** [comment]
Please check your proxy settings
