### ISSUE TITLE
WebIDE Debugger disconnected due to WebSocket Error

### ISSUE THREAD

**Issue by jcailan** [sap-archive/com.sap.openSAP.hana5.example#4]
I'm doing the XSJS debugging exercise and inspecting the variables after an xsjs file operation is suspended by a debugger breakpoint.  However, when I try to inspect the variables in the WebIDE console, the debugger will soon disconnect.  Repeating the debugging process again and again consistently result in the debugger being disconnected.  Checking on the chrome developer tools console, I can see some websocket error.  Is this an issue on webide or on-premise hana?

system: HANA 2.0 SPS02

see screenshot below for reference:

![image](https://user-images.githubusercontent.com/27951983/36490772-0c3b330c-1764-11e8-892f-d381605b7563.png)
![image](https://user-images.githubusercontent.com/27951983/36490967-91ffb49a-1764-11e8-9bf2-e4c5aa251ace.png)

**Comment by jung-thomas** [comment]
Impossible to say from this information. If you aren't using HTTPS with a trusted certificate and hostname based routing you might be having disconnect with websockets due to the untrusted nature of the connection.  However this could also be problem on the server side.  You'd have to check the di-core logs for more details.

**Comment by jcailan** [comment]
Thanks for the quick response Thomas!  

The connection is secured and using hostname based url (which is covered) -- so i guess this should be okay.

![image](https://user-images.githubusercontent.com/27951983/36492048-29a88c8e-1767-11e8-87f5-5360b8353723.png)

i could open the logs for the app core_js -- but couldn't make sense of it -- here it is:

Connected, dumping recent logs for app "JCAILAN-tu3kj370bjuohtyi-oshana5-core_js"
![image](https://user-images.githubusercontent.com/27951983/36492342-e5e38886-1767-11e8-93e4-0e057ad76ce5.png)

**Comment by jcailan** [comment]
I still couldn't figure out the issue on this.  But just to have a baseline comparison, I have setup a SAP HANA Express Edition server and found out that this issue doesn't exists in the HXE WebIDE.

Comparing versions of both HANA 2.0 SPS 02:

HXE Version: SAP Web IDE for HANA 2 SPS 02 Patch 1 ( Build 4.2.18 )
Corporate HANA Version: SAP Web IDE for HANA 2 SPS 02 Patch 4 ( Build 4.2.21 )

Surprisingly, the older patch 1 seems to be working fine compared to the Patch 4.  Probably, we will just update the Corporate HANA to the latest patch which is currently #7 and see if this solves the debugger issue.

Perhaps this issue is good to be closed.  Thanks!
